title: datumplane
email: chris@datumplane.net
description: >-
  Personal blog and technical notes
baseurl: ""
url: "https://datumplane.github.io"
twitter_username: 
github_username: datumplane

# Build settings
markdown: kramdown
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md