title: datumplane
email: chris@datumplane.net
description: >-
  Personal blog and technical notes
baseurl: "/blog"
url: "https://datumplane.net"
twitter_username: 
github_username: datumplane

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/